model_seed: 0
dataset_seed: 0
device: "cuda"
run_num: 0
data_source: 'gaussian_1'

wandb: True
sweep_config_file: "sweep_config.yaml"
project_name: "gauss_net"
experiment_tag: "gaussian_prep"
sweep: False
sweep_id: null
sweep_num_runs: 50

dataset_size: 1000
dataset_dimension: 2

batch_size: 10
epochs: 1000
history: 100
learning_rate: 0.001

model_type: mlp
model_layers: 2
model_filters: 32
model_norm: null
model_dropout: 0
model_activation: kernel